### PR TITLE
UTs failures: openssl certificate replacement and git clone submodule fix 

### PR DESCRIPTION
**Pull request by Bhavanaashok33**
1. UT failures on Libopflex due to expired certificates. Refer the previous fix: https://github.com/noironetworks/opflex/pull/332 
2. git clone and submodule fetching fails for grpc third party module if the url starts with git://. Changed the url from git:// to https://. Refer this article related to github's new security protocol:  https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
3. Reusing existing grpc cache was causing a failure. Hence removed the code to cache grpc. Everytime it will be a new git clone.

### CODE REVIEW

**Review by shastrinator — APPROVED** [review]
Thanks Bhavana. Was the local build passing without the travis changes?

**Comment by Bhavanaashok33** [comment]
> Thanks Bhavana. Was the local build passing without the travis changes?

Yes, libopflex sanities were failing on local build as well due to certificate validation failure..

**Comment by Bhavanaashok33** [comment]
and GRPC submodule fetching for third party was failing if the url format didn't satisfy the right format.. The local build is running ubuntu 20.04 where I verified these failures..

**Comment by tbachman** [comment]
Can we get this backported to the kmr2 branch?

**Comment by Bhavanaashok33** [comment]
Sure! I will backport it

**Pull request merged**
