### PR TITLE
Revert "Add flow-rules to support ICMP type/code in L24Classifier"

### PR DESCRIPTION
**Pull request by tbachman**
This reverts commit 38bc9a134322cd0c5ce1c63338b17ed91442caaa.

### CODE REVIEW

**Comment by tbachman** [comment]
Here are the before/after flow-mods:

http://paste.openstack.org/show/732305/

**Comment by tbachman** [comment]
Just some more context -- we're reverting this patch, as it's adding flow-mods that attempt to match the ICMP type and code values, which are always populated in the Host Protection Profiles sent to the agent (i.e. even if they're not used). The AIM code isn't currently configuring this state it APIC, so these values will always be (0,0). This was causing flow-mods that matched on ICMP type/code of (0,0), which is only the reply, causing ICMP traffic to get dropped.

The belief is that this patch was only made after code inspection showed that we weren't using these values, and wasn't actually needed for any functionality, and therefore can be reverted for now (until support for setting these values is added to AIM and the OpenStack plugin).

**Comment by amittbose** [comment]
IIRC, this patch was made to support ICMP rules in Cloud Foundry security groups. I guess you need type/code values that indicate "don't care" to make this work for both Neutron and CF.

**Comment by tbachman** [comment]
I'll leave this open until we've made a decision on how to handle this.

**Comment by tomflynn** [comment]
Merging this in the ganga branch only. Hopefully we can revert the revert once changes are made and tested on the AIM side

**Pull request merged**
