### PR TITLE
Backporting fixes from master

### PR DESCRIPTION
**Pull request by gautvenk**
https://github.com/noironetworks/opflex/pull/297
https://github.com/noironetworks/opflex/pull/305
https://github.com/noironetworks/opflex/pull/310
https://github.com/noironetworks/opflex/pull/312

Signed-off-by: Gautam Venkataramanan <gautam.chennai@gmail.com>

### CODE REVIEW

**Review by mchalla — APPROVED** [review]
I think it looks fine if you just cherry picked them. Not going through them in detail. My pull request to merge will have a merge conflict with these changes.

I am ok waiting on you to merge yours. I will resolve the conflict and resend after yours is merged.

**Comment by gautvenk** [comment]
> I think it looks fine if you just cherry picked them. Not going through them in detail. My pull request to merge will have a merge conflict with these changes.
> 
> I am ok waiting on you to merge yours. I will resolve the conflict and resend after yours is merged.

Thanks Madhu. Manually merged to avoid the mysterious issues of commits getting wiped off in the past.

**Comment by snaiksat** [comment]
Hi Gautam, Can we please hold off on this.

**Comment by gautvenk** [comment]
> Hi Gautam, Can we please hold off on this.

Discussed with Sumit and Tom. Leaving the PR open for now. We will hold off on these.

**Comment by tomflynn** [comment]
We're not backporting fixes to the jefferson branch any more. Closing this backport PR

**Pull request closed without merging**
