### PR TITLE
Update certificates for UTs

### PR DESCRIPTION
**Pull request by tbachman**
Commit 178b27af8085b34efff7d003bdd9cf469a90ff7d was the last time the certificate and key were updated, which are used for UTs. This patch updates them with a new set, with an expiry of 1000 days.

### CODE REVIEW

**Review by mchalla — APPROVED** [review]

**Comment by tbachman** [comment]
I was trying to fix the Codacy errors from the Markdown linter, but the existing format seems to render fine. If folks are concerned with this, I'll spend some more time trying to "fix" it, but otherwise I'd say we can merge it.

**Review by Bhavanaashok33 — APPROVED** [review]

**Comment by tbachman** [comment]
Don't merge - UTs are still failing

**Comment by tbachman** [comment]
Don't merge this yet - I have to back out the fix for the SSL packages (will rebase once the other patch has merged).

**Comment by tbachman** [comment]
I just rebased it on master - ready for review.

**Review by mchalla — APPROVED** [review]

**Pull request merged**
