### PR TITLE
Splitting mock_server and opflex_server

### PR DESCRIPTION
**Pull request by gautvenk**
- Kept mock_server under agent-ovs/cmd/test/
- Moved opflex_server to agent-ovs/server
- Removed grpc, prometheus and prr changes from mock_server
- Removed sample policy file generation from opflex_server. Rest of the options are kept intact.
- Corresponding Makefile changes
- Tested both mock and opflex server locally
- Docker script changes arent needed since opflex_server binary is still generated and accepts policy and grpc config files.

Signed-off-by: Gautam Venkataramanan <gautam.chennai@gmail.com>

### CODE REVIEW

**Comment by gautvenk** [comment]
This is to address https://github.com/noironetworks/support/issues/1202

**Comment by tomflynn** [comment]
Main reason to have both is that the mock_server by default gets started with the test policy from Policies.cpp which is useful for a bunch of unit tests. opflex_server on the other hand would never get seeded with the test policies

**Comment by gautvenk** [comment]
Hi Madhu, yes the goal is to split the functionality of mock vs real opflex server. i.e. sample policy file generation and running old mock_server with the policy file alone will be part of mock.

opflex_server will have grpc/gbpclient and prometheus integration. gbp_client_stress can now work with opflex server. Do u see any issues here?

**Comment by mchalla** [comment]
> Hi Madhu, yes the goal is to split the functionality of mock vs real opflex server. i.e. sample policy file generation and running old mock_server with the policy file alone will be part of mock.
> 
> opflex_server will have grpc/gbpclient and prometheus integration. gbp_client_stress can now work with opflex server. Do u see any issues here?

No I dont see any issues. I was just trying to avoid code duplication since the test policy seeding stuff was conditional in the original code.

**Comment by gautvenk** [comment]
> > Hi Madhu, yes the goal is to split the functionality of mock vs real opflex server. i.e. sample policy file generation and running old mock_server with the policy file alone will be part of mock.
> > opflex_server will have grpc/gbpclient and prometheus integration. gbp_client_stress can now work with opflex server. Do u see any issues here?
> 
> No I dont see any issues. I was just trying to avoid code duplication since the test policy seeding stuff was conditional in the original code.

Thank u Madhu for approving. Agreed, I understand. The main intent is to keep only sample policy generation and seeding that in mock server; and grpc/gbpclient/prometheus in opflex server. The "policy" flag is passed and used today in the docker build, so I retained that in opflex server. In theory yes the policy can be pushed via a json file directly to opflex server as well, but I guess while launching opflex server in docker, it will just be an empty json file.

**Pull request merged**
