### PR TITLE
To add new directory in opflex-agent-notif.sock path

### PR DESCRIPTION
**Pull request by ansao-aci**
New path is /var/run/opflex_notify/opflex-agent-notif.sock
This socket is to be shared by neutron_opflex_agent container and opflex_agent container.
By putting the socket file in a saperate directory inside /var/run, only that directory can be conveniently shared between
the two containers as named volume.

### CODE REVIEW

**Comment by shastrinator** [comment]
Need to make corresponding change in Makefile.am in agent-ovs for notif_sock default location and create directory under /var/run/opflex_notify in deb and rpm

**Comment by ansao-aci** [comment]
> Need to make corresponding change in Makefile.am in agent-ovs for notif_sock default location and create directory under /var/run/opflex_notify in deb and rpm


Hi Kiran,
I have made changes in the file agent-ovs/Makefile.am.  Where do I need to add the new directory in rpm/deb? 
Inside container, this directory will be created by docker via docker volume.  See following:
- opflex_socket:/run/opflex_notify

You can check out the tripleo pr here:
https://github.com/noironetworks/tripleo-ciscoaci/pull/43/files#diff-72107cc16c2792e9c410821fc45d4d9f3c17d826978c2f0820749a57abde92a9

**Comment by shastrinator** [comment]
> > Need to make corresponding change in Makefile.am in agent-ovs for notif_sock default location and create directory under /var/run/opflex_notify in deb and rpm
> 
> Hi Kiran,
> I have made changes in the file agent-ovs/Makefile.am. Where do I need to add the new directory in rpm/deb?
> Inside container, this directory will be created by docker via docker volume. See following:
> 
>     * opflex_socket:/run/opflex_notify
> 
> 
> You can check out the tripleo pr here:
> https://github.com/noironetworks/tripleo-ciscoaci/pull/43/files#diff-72107cc16c2792e9c410821fc45d4d9f3c17d826978c2f0820749a57abde92a9

In debian, it may be under debian/opflex-agent.dirs and in rpm it is under line 135 I believe, you can confirm these.

**Review by shastrinator — APPROVED** [review]

**Comment by tbachman** [comment]
Just some more context on this. There are two factors driving this change:
1) We are separating the opflex-agent and the neutron-opflex-agent into their own containers in OpenStack. This makes it easier to manage OpenStack systems, as the two agents can have their own life cycle, and can be independently restarted.
2) We are changing file and directory permissions so that our containers can be certified by Red Hat. Red Hat currently doesn't support running containers with root users.

Since Open vSwitch runs on the hypervisor, we have to bind mount the /run/openvswitch directory into the container. The current location of the notify socket under /run means that we'd have to change the permissions and/or owner of /run in order to have non-root access. This in turn affects /run from the hypervisor, which isn't what we want. As a result, we need to move it under it's own subdirectory (note: this also seems to be a more standard convention -- e.g. /run/openvswitch).

I'm also realizing that the same probably applies to the inspect socket - although I guess you could enter the container as root to run the gbp_inspect command?

**Comment by tbachman** [comment]
Actually, thinking about this a bit more, we probably shouldn't be changing the default values for the configuration, but instead handle this in our installer. I'll discuss this with Ankur and we'll determine whether or not we still need this patch.

**Pull request closed without merging**
